### ISSUE TITLE
Compile fails at ESP8266HTTPClient.cpp.o

### ISSUE THREAD

**Issue by FreeBear-nc** [phpcoder/tasmota-nexus-mqtt#1]
Complile fails at ESP8266HTTPClient.cpp.o with the following message:
```
Tasmota/tasmota/tasmota_xx2c_global/xdrv_interface.ino:537:1: error: invalid conversion from 'bool (*)(uint8_t) {aka bool (*)(unsigned char)}' to 'bool (*)(uint32_t) {aka bool (*)(unsigned int)}' [-fpermissive]
 };
```

Trivial change required to tasmota/xdrv_103_nexus_mqtt.ino:129

From:
  bool Xdrv103(uint8_t function)

to:
bool Xdrv103(uint32_t function)

(Trivial fix, not worth forking and submitting a pull request).
[fix_xdrv_compile_fail.txt](https://github.com/phpcoder/tasmota-nexus-mqtt/files/12138651/fix_xdrv_compile_fail.txt)

**Comment by phpcoder** [comment]
Thanx for the feedback.
I found that current Readme does not mention that the project is compiled for Tamota 10.0.0 where the mentioned value was of uint8_t type.
I recently updated to the version 12.5.0 my other repository [tasmota-custom-integration](https://github.com/phpcoder/tasmota-custom-integration) that gives more detail about custom tasmota driver.
This repository may need an update too.
